server:
  servlet:
    context-path: /scraper
spring:
  main:
    banner-mode: console
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd'T'HH:mm:ss
  logging:
    level:
      com.project.search: INFO

scraping:
  url: https://www.kabum.com.br/
